### ISSUE TITLE
Ouch

### ISSUE THREAD

**Issue by tyrumus** [wfhs8499Robotics/wfhs8499Robotics.github.io#1]
@qwertyiou65 It's hard on my eyes dude.  Fix it.  Now.

Just kidding.  Just wanted you to play with Github's Issues page.

**Comment by smohair** [comment]
There you go man! Fixed

**Comment by tyrumus** [comment]
Yep!  If you've solved an issue, you can click "Close and comment" when you write your comment to actually close the issue.  This will move the currently Open issue to the Closed section of your repository.

**Comment by smohair** [comment]
Cool!
